name       : smtube
version    : 21.7.0
release    : 15
source     :
    - https://sourceforge.net/projects/smtube/files/SMTube/21.7.0/smtube-21.7.0.tar.bz2 : 77e47778cd813ddaec63b5d7fba216a73e9c288cbf2f6c7488b647d264e07dc7
license    : GPL-2.0-or-later
component  : network.web
summary    : SMTube is an application that allows to browse, search and play YouTube videos.
description: |
    SMTube is an application that allows to browse, search and play YouTube videos. Videos are played back with a media player instead of a flash player, this allows better performance, particularly with HD content
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5WebKitWidgets)
rundeps    :
    - youtube-dl
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
