name       : smtube
version    : 16.7.2
release    : 1
source     :
    - http://vorboss.dl.sourceforge.net/project/smtube/SMTube/16.7.2/smtube-16.7.2.tar.bz2 : b5e636dd2db52c37f8d1a6f38653ef690268bf2b1cac34cea596d8fc0c83c44c
license    : GPL-2.0 
component  : network.web
summary    : SMTube is an application that allows to browse, search and play YouTube videos.
description: |
  SMTube is an application that allows to browse, search and play YouTube videos. Videos are played back with a media player instead of a flash player, this allows better performance, particularly with HD content
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5WebKitWidgets)
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
