name       : smtube
version    : 17.5.0
release    : 4
source     :
    - http://vorboss.dl.sourceforge.net/project/smtube/SMTube/17.5.0/smtube-17.5.0.tar.bz2 : 8dca5245e2d2be4cb472b7a6e9e7ccafa52f25b0ef2c924944aa058b02a5a08e
license    : GPL-2.0
component  : network.web
summary    : SMTube is an application that allows to browse, search and play YouTube videos.
description: |
    SMTube is an application that allows to browse, search and play YouTube videos. Videos are played back with a media player instead of a flash player, this allows better performance, particularly with HD content
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5WebKitWidgets)
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
